### ISSUE TITLE
3.0.0 todo

### ISSUE THREAD

**Issue by E66666666** [E66666666/GTAVHandlingEditor#3]
Features:
- [x] `notes.json` for parameter descriptions (WIP, 90%)
- [x] SubHandlingData (some/most may be omitted/skipped, depending on motivation):
  - [x] [CBoatHandlingData](https://gtamods.com/wiki/Handling.meta#CBoatHandlingData)
  - [x] [CBikeHandlingData](https://gtamods.com/wiki/Handling.meta#CBikeHandlingData)
  - [x] [CFlyingHandlingData](https://gtamods.com/wiki/Handling.meta#CFlyingHandlingData)
  - [x] [CVehicleWeaponHandlingData](https://gtamods.com/wiki/Handling.meta#CVehicleWeaponHandlingData)
  - [x] [CSubmarineHandlingData](https://gtamods.com/wiki/Handling.meta#CSubmarineHandlingData)
  - [x] [CTrailerHandlingData](https://gtamods.com/wiki/Handling.meta#CTrailerHandlingData)
  - [x] [CSeaPlaneHandlingData](https://gtamods.com/wiki/Handling.meta#CSeaPlaneHandlingData)
  - [x] [CSpecialFlightHandlingData](https://gtamods.com/wiki/Handling.meta#CSpecialFlightHandlingData)

Internal:
- [x] Update menu to use `SResult Option()` (WIP, 40%)

Scrapped:

- ❌ Valid" `.meta` input/output
  - ❌ Perhaps a file-browser-esque interface 
- ❌ Wheel weight display for weight distribution
- ❌ Refactor/Move a bunch of code, decrease clutter

**Comment by E66666666** [comment]
Heck, let's just call it 3.0
